env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
name: Update README with Activity

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README activity
        uses: jamesgeorge007/github-activity-readme@master
        with:
          GH_USERNAME: SuryaRaikuni

      - name: Commit changes
        run: |
          git config --global user.name "SuryaRaikuni"
          git config --global user.email "suryapratap4500@gmail.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: update activity"
          git push